package axisallies.units;

public enum Ability {
    MOVE_TO_LAND,
    MOVE_TO_SEA,
    MOVE_THROUGH_UNOCCUPIED_HOSTILE_TERRITORY,
    MOVE_THROUGH_OCCUPIED_HOSTILE_TERRITORY,
    MOVE_IN_COMBAT_MOVE,
    RESERVE_MOVES,

    CONTAINABLE,
    CONTAIN_LAND_UNITS,
    CONTAIN_AIR_UNITS,
    CONTAIN_SEA_UNITS,
    LAND_AIR_UNITS,

    SUPPORT_UNIT,
    SUPPORTING_UNIT_ATTACK_BONUS,
    ATTACK_AIR_UNITS,
    ATTACK_LAND_UNITS,
    ATTACK_SEA_UNITS,
    CAPTURE_HOSTILE_TERRITORY,
    BE_ATTACKED_BY_AIR_UNITS,
    SURPRISE_ATTACK,
    OFFSHORE_BOMBARDMENT
}

